# Generated by Django 3.2.4 on 2021-07-19 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonVariable',
            fields=[
                ('variable_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('variable_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CustodyClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_address', models.CharField(max_length=200)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(max_length=20)),
                ('client_type', models.CharField(choices=[('custodian', 'Custodian Client'), ('unittrust', 'Unit Trust')], max_length=20)),
                ('client_birthday', models.DateField(blank=True, null=True)),
                ('cds_no_cse', models.CharField(max_length=50, unique=True)),
                ('cds_no_cbsl', models.CharField(max_length=50, unique=True)),
                ('margin_interest_rate_spread', models.FloatField(blank=True, null=True)),
                ('current_account_number', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('loan_account_number', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('shariah_compliant', models.BooleanField(default=False)),
                ('risk_appetite', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], default='moderate', max_length=200)),
                ('target_returns', models.FloatField(default=0.1)),
                ('cash_balance', models.FloatField(default=0, null=True)),
                ('equity_pf_value', models.FloatField(default=0, null=True)),
                ('portfolio_value', models.FloatField(default=0, null=True)),
                ('portfolio_value_date', models.DateField(null=True)),
                ('margin_account_balance', models.FloatField(default=0)),
                ('margin_account_balance_date', models.DateField(auto_now_add=True)),
                ('maximum_margin', models.FloatField(default=0)),
                ('maximum_margin_date', models.DateField(auto_now_add=True)),
                ('payable_amount', models.FloatField(default=0)),
                ('payable_amount_date', models.DateField(auto_now_add=True)),
                ('receivable_amount', models.FloatField(default=0)),
                ('receivable_amount_date', models.DateField(auto_now_add=True)),
                ('unit_trust_name', models.CharField(max_length=200, null=True)),
                ('unit_trust_description', models.TextField(null=True)),
                ('unit_bid_price', models.FloatField(null=True)),
                ('unit_ask_price', models.FloatField(null=True)),
                ('number_of_units', models.FloatField(null=True)),
                ('custodian_fee_type', models.CharField(choices=[('fixed', 'Flat fee'), ('flatpct', 'Flat Rate on AUM'), ('slabstotasses', 'Variable slabs for AUM'), ('slabsbyassettype', 'Variable slabs by instrument')], default='fixed', max_length=200)),
                ('custodian_fee_fixed_value', models.PositiveIntegerField(default=0, null=True)),
                ('custodian_fee_pct_value', models.PositiveIntegerField(default=0, null=True)),
                ('fund_manager_fee_rate', models.FloatField(default=0.02)),
            ],
        ),
        migrations.CreateModel(
            name='EquityTrade',
            fields=[
                ('trade_price', models.FloatField()),
                ('trade_quantity', models.FloatField()),
                ('trade_date', models.DateField()),
                ('settlement_date', models.DateField()),
                ('trade_direction', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('brokerage', models.FloatField(default=0)),
                ('cds_fees', models.FloatField(default=0)),
                ('sec_cess', models.FloatField(default=0)),
                ('btt', models.FloatField(default=0)),
                ('cse_fees', models.FloatField(default=0)),
                ('stamp_duty', models.FloatField(default=0)),
                ('govt_cess', models.FloatField(default=0)),
                ('trx_contract', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('disputed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FeeReceipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipient_name', models.CharField(max_length=100)),
                ('bank_account_no', models.PositiveIntegerField()),
                ('bank_name', models.CharField(max_length=50)),
                ('account_branch', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ListedEquity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('isin', models.CharField(max_length=200, null=True)),
                ('company_name', models.CharField(max_length=100)),
                ('current_price', models.FloatField()),
                ('current_price_date', models.DateField()),
                ('in_sl20', models.BooleanField()),
                ('margin_pct', models.FloatField(default=0.5)),
            ],
        ),
        migrations.CreateModel(
            name='StockBroker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_name', models.CharField(max_length=200)),
                ('broker_code', models.CharField(default='AAA', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('uploaded_file', models.FileField(upload_to='')),
                ('uploaded_by', models.CharField(blank=True, max_length=200, null=True)),
                ('upload_type', models.CharField(choices=[('equityprices', 'Equity Price List'), ('cdstrades', 'CDS Trade List')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MarginAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_account_sweep', models.BooleanField(default=False)),
                ('trade_date', models.DateField()),
                ('settlement_date', models.DateField(null=True)),
                ('debit', models.BooleanField(null=True)),
                ('amount', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custodian.custodyclient')),
                ('trade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custodian.equitytrade')),
            ],
        ),
        migrations.AddField(
            model_name='equitytrade',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custodian.stockbroker'),
        ),
        migrations.AddField(
            model_name='equitytrade',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custodian.custodyclient'),
        ),
        migrations.AddField(
            model_name='equitytrade',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custodian.listedequity'),
        ),
        migrations.CreateModel(
            name='EquityHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('cost_basis', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('broker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='custodian.stockbroker')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custodian.custodyclient')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custodian.listedequity')),
            ],
        ),
        migrations.CreateModel(
            name='DividendAnnouncements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dividend_amount', models.FloatField()),
                ('ex_date', models.DateField()),
                ('updated_date', models.DateField(auto_now_add=True)),
                ('equity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custodian.listedequity')),
            ],
        ),
        migrations.AddField(
            model_name='custodyclient',
            name='fee_receipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custodian.feereceipient'),
        ),
        migrations.CreateModel(
            name='CurrentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('amount', models.FloatField()),
                ('narration', models.CharField(max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custodian.custodyclient')),
            ],
        ),
        migrations.CreateModel(
            name='ClientHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_value', models.FloatField()),
                ('margin_balance', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custodian.custodyclient')),
            ],
        ),
        migrations.CreateModel(
            name='ClientBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_date', models.DateField(auto_now_add=True)),
                ('pf_value', models.FloatField()),
                ('margin_value', models.FloatField()),
                ('margin_balance', models.FloatField(null=True)),
                ('pf_cost', models.FloatField()),
                ('unit_bid_price', models.FloatField(null=True)),
                ('unit_ask_price', models.FloatField(null=True)),
                ('number_of_units', models.FloatField(null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custodian.custodyclient')),
            ],
        ),
        migrations.CreateModel(
            name='CDSAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_transfer_to_CDS', models.BooleanField(default=False)),
                ('trade_date', models.DateField()),
                ('settlement_date', models.DateField()),
                ('credit', models.BooleanField()),
                ('amount', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custodian.custodyclient')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custodian.equitytrade')),
            ],
        ),
        migrations.CreateModel(
            name='AccruedCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_date', models.DateField(auto_now_add=True)),
                ('fee_type', models.CharField(choices=[('custodyfee', 'Custody Fee'), ('margininterest', 'Margin Interest')], max_length=200)),
                ('fee_amount', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custodian.custodyclient')),
                ('receipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custodian.feereceipient')),
            ],
        ),
    ]
