# Generated by Django 3.2.4 on 2021-07-02 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custodian', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='current_account_balance',
        ),
        migrations.RemoveField(
            model_name='client',
            name='current_account_balance_date',
        ),
        migrations.AddField(
            model_name='client',
            name='portfolio_value',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='portfolio_value_date',
            field=models.DateField(null=True),
        ),
    ]
