# Generated by Django 3.2.4 on 2021-07-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custodian', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custodyclient',
            name='client_id',
        ),
        migrations.AlterField(
            model_name='custodyclient',
            name='cds_no_cbsl',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='custodyclient',
            name='cds_no_cse',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='custodyclient',
            name='unit_trust_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
