# Generated by Django 3.2.4 on 2021-07-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custodian', '0002_auto_20210718_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custodyclient',
            name='maximum_margin_date',
            field=models.DateField(auto_now=True),
        ),
    ]
