# Generated by Django 3.2.4 on 2021-07-05 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custodian', '0003_auto_20210704_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cds_no_cbsl',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='cds_no_cse',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('custodian', 'Custodian Client')], max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='current_account_number',
            field=models.FloatField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='loan_account_number',
            field=models.FloatField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dividendannouncements',
            name='updated_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='ClientBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_date', models.DateField(auto_now_add=True)),
                ('pf_value', models.FloatField()),
                ('margin_value', models.FloatField()),
                ('margin_balance', models.FloatField()),
                ('pf_cost', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custodian.client')),
            ],
        ),
    ]
