# Generated by Django 3.2.4 on 2021-07-05 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custodian', '0006_auto_20210705_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marginaccount',
            name='debit',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='marginaccount',
            name='settlement_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='marginaccount',
            name='trade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custodian.equitytrade'),
        ),
    ]
