# Generated by Django 3.2.4 on 2021-07-13 16:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.CharField(max_length=200)),
                ('borrower_address', models.CharField(max_length=300)),
                ('borrower_contact_name', models.CharField(max_length=200)),
                ('borrower_contact_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_id_no', models.IntegerField()),
                ('investor_name', models.CharField(max_length=200)),
                ('investor_address', models.CharField(max_length=300)),
                ('investor_nic', models.CharField(blank=True, max_length=20)),
                ('investor_account_no', models.CharField(max_length=50)),
                ('investor_account_branch', models.CharField(max_length=100)),
                ('investor_account_bank', models.CharField(max_length=50)),
                ('investor_email', models.EmailField(max_length=254)),
                ('investor_phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Securitization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_name', models.CharField(max_length=200)),
                ('arranger_name', models.CharField(max_length=200)),
                ('amount_raised', models.IntegerField()),
                ('expected_sign_date', models.CharField(blank=True, max_length=200)),
                ('td_firstdraft', models.FileField(upload_to='')),
                ('trust_name', models.CharField(blank=True, default='', max_length=200)),
                ('trust_bank_account_no', models.CharField(blank=True, default='', max_length=200)),
                ('trust_bank_account_branch', models.CharField(blank=True, default='', max_length=200)),
                ('trust_bank_account_bank', models.CharField(blank=True, default='', max_length=200)),
                ('lawyer_name', models.CharField(max_length=200)),
                ('auditor_name', models.CharField(max_length=200)),
                ('trustee_approved', models.BooleanField(default=False)),
                ('deal_signed', models.BooleanField(default=False)),
                ('cashflow_checked', models.BooleanField(default=False)),
                ('deal_signed_date', models.DateField(blank=True, null=True)),
                ('td_completedraft', models.FileField(blank=True, upload_to='')),
                ('td_completesigned', models.FileField(blank=True, upload_to='')),
                ('board_resolution', models.FileField(blank=True, upload_to='')),
                ('information_memo', models.FileField(blank=True, upload_to='')),
                ('audit_report', models.FileField(blank=True, upload_to='')),
                ('investor_schedule_file', models.FileField(blank=True, upload_to='')),
                ('investments_file', models.FileField(blank=True, upload_to='')),
                ('security_list_file', models.FileField(blank=True, upload_to='')),
                ('trust_certificates', models.FileField(blank=True, upload_to='')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trusteeapp.borrower')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('transfer_date', models.DateField()),
                ('transfer_complete', models.BooleanField(default=False)),
                ('borrower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='trusteeapp.borrower')),
                ('investor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='trusteeapp.investor')),
                ('securitization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trusteeapp.securitization')),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateField()),
                ('removed_date', models.DateField(blank=True, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=30, null=True)),
                ('engine_number', models.CharField(max_length=30)),
                ('chassis_number', models.CharField(max_length=30)),
                ('make', models.CharField(blank=True, max_length=30, null=True)),
                ('model', models.CharField(blank=True, max_length=30, null=True)),
                ('lessee_name', models.CharField(blank=True, max_length=200, null=True)),
                ('lessee_nic', models.CharField(blank=True, max_length=15, null=True)),
                ('lessee_address', models.CharField(blank=True, max_length=200, null=True)),
                ('loan_amount', models.FloatField(blank=True, null=True)),
                ('interest_rate', models.FloatField(blank=True, null=True)),
                ('monthly_payment', models.FloatField()),
                ('last_payment_date', models.DateField()),
                ('days_in_arrears', models.PositiveIntegerField(blank=True, null=True)),
                ('securitization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trusteeapp.securitization')),
            ],
        ),
        migrations.AddField(
            model_name='investor',
            name='securitization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trusteeapp.securitization'),
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('investment_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('interest_rate_type', models.PositiveSmallIntegerField(choices=[(1, 'Fixed'), (2, 'AWPLR+')])),
                ('fixed_interest_rate', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('variable_rate_spread', models.FloatField(blank=True, null=True)),
                ('variable_rate_reset_freq', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('variable_rate_floor', models.FloatField(blank=True, null=True)),
                ('variable_rate_cap', models.FloatField(blank=True, null=True)),
                ('funds_received', models.BooleanField(default=False)),
                ('maturity_proceeds_transfered', models.BooleanField(default=False)),
                ('withheld_tax', models.FloatField(blank=True, default=0)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trusteeapp.investor')),
                ('securitization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trusteeapp.securitization')),
            ],
        ),
    ]
