# Generated by Django 3.2.4 on 2021-06-21 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trusteeapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deal',
        ),
    ]
