# Generated by Django 3.2.4 on 2021-06-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trusteeapp', '0002_delete_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitization',
            name='audit_report',
            field=models.FileField(blank=True, upload_to='documents'),
        ),
        migrations.AddField(
            model_name='securitization',
            name='board_resolution',
            field=models.FileField(blank=True, upload_to='documents'),
        ),
        migrations.AddField(
            model_name='securitization',
            name='td_completedraft',
            field=models.FileField(blank=True, upload_to='documents'),
        ),
        migrations.AddField(
            model_name='securitization',
            name='td_completesigned',
            field=models.FileField(blank=True, upload_to='documents'),
        ),
    ]
