# Generated by Django 3.2.4 on 2021-06-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trusteeapp', '0003_auto_20210621_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitization',
            name='deal_signed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
