# Generated by Django 3.2.4 on 2021-06-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trusteeapp', '0004_securitization_deal_signed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitization',
            name='trust_bank_account_bank',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='securitization',
            name='trust_bank_account_branch',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='securitization',
            name='trust_bank_account_no',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
