# Generated by Django 3.2.4 on 2021-06-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trusteeapp', '0005_auto_20210621_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitization',
            name='amount_raised',
            field=models.IntegerField(default=100000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securitization',
            name='expected_sign_date',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
