# Generated by Django 3.2.4 on 2021-06-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trusteeapp', '0006_auto_20210621_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitization',
            name='arranger_name',
            field=models.CharField(default='Liege', max_length=200),
            preserve_default=False,
        ),
    ]
