# Generated by Django 3.2.4 on 2021-06-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trusteeapp', '0007_securitization_arranger_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitization',
            name='cashflow_checked',
            field=models.BooleanField(default=False),
        ),
    ]
