# Generated by Django 3.2.4 on 2021-06-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trusteeapp', '0009_auto_20210621_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitization',
            name='information_memo',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='securitization',
            name='td_firstdraft',
            field=models.FileField(upload_to=''),
        ),
    ]
