# Generated by Django 3.2.4 on 2021-06-22 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trusteeapp', '0010_auto_20210621_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitization',
            name='investments_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='securitization',
            name='investor_schedule_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='securitization',
            name='trust_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_id_no', models.IntegerField()),
                ('investor_name', models.CharField(max_length=200)),
                ('investor_address', models.CharField(max_length=300)),
                ('investor_nic', models.CharField(blank=True, max_length=20)),
                ('investor_account_no', models.CharField(max_length=50)),
                ('investor_account_branch', models.CharField(max_length=100)),
                ('investor_account_bank', models.CharField(max_length=50)),
                ('investor_email', models.EmailField(max_length=254)),
                ('investor_phone', models.CharField(max_length=20)),
                ('securitization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trusteeapp.securitization')),
            ],
        ),
    ]
