# Generated by Django 3.2.4 on 2021-06-22 18:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trusteeapp', '0011_auto_20210621_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('investment_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('interest_rate_type', models.PositiveSmallIntegerField(choices=[(1, 'Fixed'), (2, 'AWPLR+')])),
                ('fixed_interest_rate', models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('variable_rate_spread', models.FloatField(blank=True)),
                ('variable_rate_reset_freq', models.PositiveSmallIntegerField(blank=True)),
                ('variable_rate_floor', models.FloatField(blank=True)),
                ('variable_rate_cap', models.FloatField(blank=True)),
                ('funds_received', models.BooleanField(default=False)),
                ('maturity_proceeds_transfered', models.BooleanField(default=False)),
                ('withheld_tax', models.FloatField(blank=True, default=0)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trusteeapp.investor')),
                ('securitization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trusteeapp.securitization')),
            ],
        ),
    ]
