# Generated by Django 3.2.4 on 2021-06-24 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trusteeapp', '0014_auto_20210622_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitization',
            name='security_list_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateField()),
                ('removed_date', models.DateField(blank=True, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=30, null=True)),
                ('engine_number', models.CharField(max_length=30)),
                ('chassis_number', models.CharField(max_length=30)),
                ('make', models.CharField(blank=True, max_length=30, null=True)),
                ('model', models.CharField(blank=True, max_length=30, null=True)),
                ('lessee_name', models.CharField(blank=True, max_length=200, null=True)),
                ('lessee_nic', models.CharField(blank=True, max_length=15, null=True)),
                ('lessee_address', models.CharField(blank=True, max_length=200, null=True)),
                ('loan_amount', models.FloatField(blank=True, null=True)),
                ('interest_rate', models.FloatField(blank=True, null=True)),
                ('monthly_payment', models.FloatField()),
                ('last_payment_date', models.DateField()),
                ('days_in_arrears', models.PositiveIntegerField(blank=True, null=True)),
                ('securitization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trusteeapp.securitization')),
            ],
        ),
    ]
