# Generated by Django 3.2.4 on 2021-07-19 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custodian', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitTrustHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_units', models.IntegerField(default=0)),
                ('cost_basis', models.FloatField(default=0)),
                ('nick_name', models.CharField(max_length=100)),
                ('investment_objective', models.CharField(max_length=200)),
                ('time_horizon', models.PositiveIntegerField()),
                ('investment_frequency', models.CharField(choices=[('weekly', 'Every week'), ('monthly', 'Every month'), ('quarterly', 'Every quarter'), ('annually', 'Every year')], max_length=50)),
                ('investment_amount', models.FloatField()),
                ('unit_trust', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custodian.custodyclient')),
            ],
        ),
        migrations.CreateModel(
            name='UnitTrustInvestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.PositiveIntegerField()),
                ('bank_account_number', models.PositiveIntegerField()),
                ('bank_name', models.CharField(max_length=100)),
                ('branch_name', models.CharField(max_length=100)),
                ('bank_statement', models.FileField(null=True, upload_to='')),
                ('nic_number', models.CharField(max_length=20)),
                ('nic_copy_side1', models.FileField(null=True, upload_to='')),
                ('nic_copy_side2', models.FileField(null=True, upload_to='')),
                ('headshot', models.FileField(null=True, upload_to='')),
                ('account_open_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitTrustHoldingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_date', models.DateField(auto_now_add=True)),
                ('number_of_units', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('unit_trust_holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compound.unittrustholding')),
            ],
        ),
        migrations.AddField(
            model_name='unittrustholding',
            name='unit_trust_investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compound.unittrustinvestor'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Unit purchase'), ('redemption', 'Unit redemption'), ('transfer', 'Fund transfer to investor')], max_length=50)),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('purchase_amount', models.FloatField(blank=True, null=True)),
                ('purchase_price', models.FloatField(null=True)),
                ('number_of_units_purchased', models.FloatField(null=True)),
                ('redemption_amount', models.FloatField(null=True)),
                ('redemption_price', models.FloatField(null=True)),
                ('number_of_units_redeemed', models.FloatField(null=True)),
                ('transaction_processed', models.BooleanField(default=False)),
                ('unit_trust_holding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compound.unittrustholding')),
            ],
        ),
    ]
